{% set name = "scikit-learn-intelex" %}
{% set version = "2021.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/scikit-learn-intelex/archive/{{ version }}.tar.gz
  sha256: a75acdc518f0af262a86952ee1040d5c8b9a9dbd4bf798fd974a917ee5b47e68
  patches:
    - patches/0002-win-64-py37-distutils.patch

build:
  number: 0
  script: {{ PYTHON }} setup_sklearnex.py install --single-version-externally-managed --record=record.txt
  skip: True    # [not ((win or linux or osx) and x86_64)]
  skip: True    # [py<37]

requirements:
  build:
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - python
    - setuptools
  run:
    - python
    - daal4py {{ version }}
    - scikit-learn <1.1

test:
  requires:
    - pandas
    - pytest
  source_files:
    - sklearnex/tests
  commands:
    - cd sklearnex
    - python -c "import sklearnex"
    - python -c "from sklearnex import patch_sklearn; patch_sklearn()"
    - python -m pytest .

about:
  home: https://intel.github.io/scikit-learn-intelex
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - doc/third-party-programs-sklearnex.txt
  summary: Intel(R) Extension for Scikit-learn is a seamless way to speed up your Scikit-learn application.
  dev_url: https://github.com/intel/scikit-learn-intelex
  doc_url: https://intel.github.io/scikit-learn-intelex

extra:
  recipe-maintainers:
    - napetrov
    - vmeshche
    - Pahandrovich
    - itearsl
